### ISSUE TITLE
在执行51行后，无结果直接跳转到running complete

### ISSUE THREAD

**Issue by whale-song** [IllusiveBull/nonebot_plugin_pokemonfusion#1]
今晚刚装上，结果一直无法输出正常结果。故尝试在关键步骤插入print语句排查，发现在执行源码51行（res = await ...）后未执行后续命令直接跳转至任务结束，如下图所示：
![image](https://user-images.githubusercontent.com/43376589/234367497-51007df7-8c33-4581-9876-36c04caf09ad.png)
![image](https://user-images.githubusercontent.com/43376589/234367686-1e8d36bf-7d06-4813-8121-6013554cdbcd.png)
执行完51行后的print未执行，后续无任何输出。

**Comment by IllusiveBull** [comment]
检查一下是否有系统代理和url能不能直接访问？

**Comment by whale-song** [comment]
没有挂系统代理，url服务器端是能ping得通的（丢包63%），是不是该挂个代理

**Comment by IllusiveBull** [comment]
> 没有挂系统代理，url服务器端是能ping得通的（丢包63%），是不是该挂个代理

ghproxy是代理过的，可以试试把ghproxy去掉？我在国外不太了解情况，ghproxy是发布的时候被人建议加上的

**Comment by am-q** [comment]
> > 没有挂系统代理，url服务端是能ping通的（丢包63%），是不是该挂个代理
> 
> ghproxy是代理过的，可以试把ghproxy去掉吗？我在国外不太了解情况，ghproxy是发布的时候被人建议加的

ghproxy没必要加，能访问git的都有办法上，加了反而无法正常使用，我前两天也遇到了同样的困扰

**Comment by IllusiveBull** [comment]
> > > 没有挂系统代理，url服务端是能ping通的（丢包63%），是不是该挂个代理
> > 
> > 
> > ghproxy是代理过的，可以试把ghproxy去掉吗？我在国外不太了解情况，ghproxy是发布的时候被人建议加的
> 
> ghproxy没必要加，能访问git的都有办法上，加了反而无法正常使用，我前两天也遇到了同样的困扰

已经删掉了，谢谢
