### ISSUE TITLE
是不是以后就不了了

### ISSUE THREAD

**Issue by WTTSFW** [IllusiveBull/nonebot_plugin_pokemonfusion#3]

**Comment by IllusiveBull** [comment]
刚刚去discord找到了新的网址，已经更新发布了，国内镜像源可能还得等一两天

**Comment by RainbowDashKira** [comment]
> 刚刚去discord找到了新的网址，已经更新发布了，国内镜像源可能还得等一两天

你好，找到个国内延迟低一点的（我自己ping，比原来的https://fusioncalc.com/快了3倍，也不会丢包）https://infinitefusion.gitlab.io/pokemon/ ，不确定是不是最新的，不过页面上也写了第七世代，不知道咋替换，大佬有空的话可以看一下 。
看懂了，https://gitlab.com/infinitefusion/sprites/-/raw/master/CustomBattlers/
               https://gitlab.com/infinitefusion/sprites/-/raw/master/Battlers/

**Comment by IllusiveBull** [comment]
> > 刚刚去discord找到了新的网址，已经更新发布了，国内镜像源可能还得等一两天
> 
> 你好，找到个国内延迟低一点的（我自己ping，比原来的[https://fusioncalc.com/快了3倍，也不会丢包）https://infinitefusion.gitlab.io/pokemon/](https://fusioncalc.com/%E5%BF%AB%E4%BA%863%E5%80%8D%EF%BC%8C%E4%B9%9F%E4%B8%8D%E4%BC%9A%E4%B8%A2%E5%8C%85%EF%BC%89https://infinitefusion.gitlab.io/pokemon/) ，不确定是不是最新的，不过页面上也写了第七世代，不知道咋替换，大佬有空的话可以看一下 。 看懂了，https://gitlab.com/infinitefusion/sprites/-/raw/master/CustomBattlers/ https://gitlab.com/infinitefusion/sprites/-/raw/master/Battlers/

源码已经更新了，加了配置项，在传pypi
