### ISSUE TITLE
关于返回的图片是autogen生成的还是custom的问题

### ISSUE THREAD

**Issue by RainbowDashKira** [IllusiveBull/nonebot_plugin_pokemonfusion#4]
发送指令不论是融合1 2 还是融合2 1，都是返回两张autogen，但是网页上可以发现其中一张应是有custom版的。比如喷火龙charizard和泥巴鱼stunfisk。是否可以让其优先选择custom版，或者在正确融合顺序的时候选择custom，比如上面说的喷火龙泥巴鱼是先喷火龙后泥巴鱼（6,420）

**Comment by IllusiveBull** [comment]
抱歉没注意到两个图片源地址格式不一样导致gitlab那个源只有fallback的autogen版……已改

**Comment by RainbowDashKira** [comment]
谢谢
